module.exports = [
    {
        id_league: 1,
        league_owner: 1,
        name: 'Ultimate Basketball League',
        address: '589 Basketball Drive',
        city: 'Toronto',
        province: 'Ontario',
        country: 'Canada',
        postal_code: 'M4W 3Y3',
        sport: 'Basketball',
        gender: "Men's",
        price: 299,
        start_date: 'December 14, 2022',
        end_date: 'March 13, 2023',
        description: 'The best basketball league in Toronto.'
    },
    {
        id_league: 2,
        league_owner: 1,
        name: 'Cams Awesome Curling League',
        address: '750 Daly Street',
        city: 'Winnipeg',
        province: 'Manitoba',
        country: 'Canada',
        postal_code: 'M4W 3Y3',
        sport: 'Curling',
        gender: 'Co-Ed',
        price: 199,
        start_date: 'September 2, 2023',
        end_date: 'March 8, 2024',
        description: 'Winnipeg top rated curling league.'
    },
    {
        id_league: 3,
        league_owner: 2,
        name: 'Thyrones Champion Basketball League',
        address: '55 Yonge Street',
        city: 'Toronto',
        province: 'Ontario',
        country: 'Canada',
        postal_code: 'M4W 3Y3',
        sport: 'Basketball',
        gender: "Women's",
        price: 399,
        start_date: 'April 2, 2023',
        end_date: 'July 6, 2023',
        description: 'Come play in the only league for champions only.'
    },
    {
        id_league: 4,
        league_owner: 2,
        name: 'Royal Canadian Curling Club',
        address: '131 Broadview Avenue',
        city: 'Toronto',
        province: 'Ontario',
        country: 'Canada',
        postal_code: 'R9N 8Y7',
        sport: 'Curling',
        gender: "Co-Ed",
        price: 399,
        start_date: 'February 5, 2023',
        end_date: 'June 23, 2023',
        description: 'Toronto top rated curling league, where the sweepers only sweep hard.'
    },
    {
        id_league: 5,
        league_owner: 1,
        name: 'U of W Adult Basketball League',
        address: 'University of Winnipeg',
        city: 'Winnipeg',
        province: 'Manitoba',
        country: 'Canada',
        postal_code: 'R9N 8Y7',
        sport: 'Basketball',
        gender: "Men's",
        price: 399,
        start_date: 'December 13, 2022',
        end_date: 'May 3, 2023',
        description: 'Join us in the longest running basketball league to hit Winnipeg.'
    }
]