module.exports = [
    {
        id: 1,
        first_name: 'Cameron',
        last_name: 'Makarchuk',
        email: 'test@test.com',
        address: '123 Somewhere Lane',
        city: 'Toronto',
        province: 'Ontario',
        country: 'Canada',
        postal_code: 'M4W 3Y3',
        avatar_img: '',
        password: '1234',
        is_league_owner: true,
    },
    {
        id: 2,
        first_name: 'Tugs',
        last_name: 'Morrison',
        email: 'dog@doggy.com',
        address: '589 Doggo Way',
        city: 'Toronto',
        province: 'Ontario',
        country: 'Canada',
        postal_code: 'M4W 3Y3',
        avatar_img: '',
        password: '1234',
        is_league_owner: false,
    },
    {
        id: 3,
        first_name: 'Kate',
        last_name: 'Morrison',
        email: 'kate@test.com',
        address: '189 Bloor Street',
        city: 'Toronto',
        province: 'Ontario',
        country: 'Canada',
        postal_code: 'M4W 3Y3',
        avatar_img: '',
        password: '1234',
        is_league_owner: false,
    }
]